#!/usr/bin/env bash
BENCHMARK_NAME="DenseGaussianMixture"
PACKAGE="skydata.spark.benchmark.clustering"
CLASS="${PACKAGE}.${BENCHMARK_NAME}Benchmark"

DIR=`dirname "$0"`
DIR=`cd "$DIR"/..; pwd`
DATA_DIR="${DIR}/data/$BENCHMARK_NAME"
OUTPUT_DIR="${DIR}/result"

#DATA_GEN_ARG=
NUM_OF_POINTS=200
NUM_OF_CLUSTERS=20
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=30
DATA_GEN_ARG="${NUM_OF_POINTS} ${NUM_OF_CLUSTERS} ${DIMENSIONS} ${SCALING} ${NUM_OF_PARTITIONS}"



#ALG_ARG=
CONVERGENCE_TOL="0.1"
MAX_ITERATION="20"
ALG_ARG="${CONVERGENCE_TOL} ${MAX_ITERATION}"
