#!/usr/bin/env bash


CLASS="KmeansBenchmark"
DIR=`dirname "$0"`
DIR=`cd "$DIR"/..; pwd`
DATA_DIR="${DIR}/data/$CLASS"
OUTPUT_DIR="${DIR}/result/$CLASS"

NUM_OF_CLUSTERS=20
MAX_ITERATION=20
NUM_RUN=1

NUM_OF_POINTS=100
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=10
OPTION="${DATA_DIR} ${OUTPUT_DIR} ${NUM_OF_CLUSTERS} ${MAX_ITERATION} ${NUM_RUN} ${NUM_OF_POINTS} ${DIMENSIONS} ${SCALING} ${NUM_OF_PARTITIONS}"

