#!/usr/bin/env bash


CLASS="skydata.spark.benchmark.KmeansBenchmark"
BENCHMARK_NAME="Kmeans"
DIR=`dirname "$0"`
DIR=`cd "$DIR"/..; pwd`
DATA_DIR="${DIR}/data/$BENCHMARK_NAME"
OUTPUT_DIR="${DIR}/result"


NUM_OF_POINTS=100
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=10
DATA_GEN_ARG="${NUM_OF_POINTS} ${DIMENSIONS} ${SCALING} ${NUM_OF_PARTITIONS}"



NUM_OF_CLUSTERS=20
MAX_ITERATION=20
NUM_RUN=1
ALG_ARG="${NUM_OF_CLUSTERS} ${MAX_ITERATION} ${NUM_RUN}"
