#!/usr/bin/env bash


BENCHMARK_NAME="Kmeans"
PACKAGE="skydata.spark.benchmark.clustering"
CLASS="${PACKAGE}.${BENCHMARK_NAME}Benchmark"
DIR=`dirname "$0"`
DIR=`cd "$DIR"/..; pwd`
DATA_DIR="${DIR}/data/$BENCHMARK_NAME"
OUTPUT_DIR="${DIR}/result"

NUM_OF_POINTS=10
NUM_OF_CLUSTERS=20
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=30
DATA_GEN_ARG="${NUM_OF_POINTS} ${DIMENSIONS} ${SCALING} ${NUM_OF_PARTITIONS}"




MAX_ITERATION=20
RUNS=2
ALG_ARG="${NUM_OF_CLUSTERS} ${MAX_ITERATION} ${RUNS}"
